# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: "^.vscode/" # vscode autogenerates these files
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
        exclude: .vscode/ # vscode .json files have comments, so not valid JSON
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: no-commit-to-branch # blocks commiting to `main`/`master`
    -   id: mixed-line-ending
        # prevent Windows CRLF line ending, and use LF (Unix) line ending
        args: ["--fix=lf"]
    # Python-only-checks
    -   id: check-ast # check whether valid Python
    -   id: check-docstring-first # check Python doc-string location
    -   id: debug-statements # forbid committing Python debug statements
