name: Tests

# This action should run on every commit
on: [push, pull_request]
env:
  # override poetry virtual env location
  # required for actions/setup-python@v3 can cache poetry correctly
  POETRY_VIRTUALENVS_IN_PROJECT: false

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v2.0.3
        env:
          # skip the check that throws on `main` branch
          SKIP: no-commit-to-branch
  lint-d3:
    name: Lint D3 claims
    # Ideally this would be part of the .pre-commit-config.yaml,
    # but pre-commit cannot install python dependencies that are
    # not in the root folder of a Git repo (it's a subfolder).
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          # Turris Omnia uses Python 3.7.13
          python-version: '3.7.13'
          cache: 'pip'
          cache-dependency-path: 'd3-scripts/poetry.lock'
      - name: Install d3-scripts
        run: pip install ./d3-scripts
      - name: Lint D3 claims
        run: d3lint manufacturers/**/*.d3.yaml
  test:
    name: Test Python scripts
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: d3-scripts
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v3
        with:
          # Turris Omnia uses Python 3.7.13
          python-version: '3.7.13'
          cache: 'poetry'
      - run: poetry install
      - run: poetry run pytest # tests whether our Python code works
  d3build:
    name: Run D3 Build
    runs-on: ubuntu-latest
    # d3build is slow, so only run if lint/tests pass
    needs: [pre-commit, test]
    defaults:
      run:
        working-directory: d3-scripts
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v3
        with:
          python-version: '3'
          cache: 'poetry'
      - run: poetry install
      - run: poetry run d3build
      # todo, commit the ../manufacturers_json/ dir to a new branch
