name: Tests

# This action should run on every commit
on: [push, pull_request]
env:
  # override poetry virtual env location
  # required for actions/setup-python@v3 can cache poetry correctly
  POETRY_VIRTUALENVS_IN_PROJECT: false

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v2.0.3
        env:
          # skip the check that throws on `main` branch
          SKIP: no-commit-to-branch
  d3lint:
    name: Lint D3 claims
    # Ideally this would be part of the .pre-commit-config.yaml,
    # but pre-commit cannot install python dependencies that are
    # not in the root folder of a Git repo (it's a subfolder).
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.8'
          cache: 'pip'
      - name: Install d3-cli
        run: pip install d3-cli
      - name: Lint D3 claims
        run: d3-cli manufacturers --mode lint
  d3build:
    name: Run D3 Build
    permissions:
      # required to make a new commit in the `csv` branch
      contents: write
    runs-on: ubuntu-latest
    # d3build is slow, so only run if lint passes
    needs: [pre-commit, d3lint]
    # Only run on main branch, as the build is resource intensive
    if:
      contains('
        refs/heads/main
      ', github.ref)
    defaults:
      run:
        working-directory: d3-scripts
    steps:
      - uses: actions/checkout@v3
      - name: Install d3-cli
        run: pip install d3-cli
      - name: Validate D3 files, convert to JSON and Export D3 JSON files into CSV
        run: d3-cli manufacturers --mode export
      - name: Deploy CSV files to `csv` branch (`main` branch only)
        if: github.ref == 'refs/heads/main'
        uses: s0/git-publish-subdir-action@v2.5.1
        env:
          REPO: self
          BRANCH: csv
          FOLDER: D3DB
          SKIP_EMPTY_COMMITS: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
