name: Tests

# This action should run on every commit
on: [push, pull_request]
env:
  # override poetry virtual env location
  # required for actions/setup-python@v3 can cache poetry correctly
  POETRY_VIRTUALENVS_IN_PROJECT: false

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v2.0.3
        env:
          # skip the check that throws on `main` branch
          SKIP: no-commit-to-branch
  test:
    name: Test Python scripts
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: d3-scripts
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v3
        with:
          # Turris Omnia uses Python 3.7.13
          python-version: '3.7.13'
          cache: 'poetry'
      - run: poetry install
      - run: poetry run pytest # tests whether our Python code works
  d3build:
    name: Run D3 Build
    permissions:
      # required to make a new commit in the `csv` branch
      contents: write
    runs-on: ubuntu-latest
    # d3build is slow, so only run if lint/tests pass
    needs: [pre-commit, test]
    defaults:
      run:
        working-directory: d3-scripts
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v3
        with:
          python-version: '3'
          cache: 'poetry'
      - run: poetry install
      - name: Validate D3 files and convert to JSON
        run: poetry run d3build
      - name: Export D3 JSON files into CSV
        run: poetry run d3export
      - name: Deploy CSV files to `csv` branch (`main` branch only)
        if: github.ref == 'refs/heads/main'
        uses: s0/git-publish-subdir-action@v2.5.1
        env:
          REPO: self
          BRANCH: csv
          FOLDER: D3DB
          SKIP_EMPTY_COMMITS: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
